/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uts_Denis;

/**
 *
 * @author ACER
 */
public class GantiPin extends javax.swing.JFrame {

    /**
     * Creates new form GantiPin
     */
    public GantiPin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        berhasil2 = new javax.swing.JLabel();
        berhasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(805, 428));
        setMinimumSize(new java.awt.Dimension(805, 428));
        setPreferredSize(new java.awt.Dimension(805, 428));
        setSize(new java.awt.Dimension(805, 428));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        berhasil2.setBackground(new java.awt.Color(255, 255, 255));
        berhasil2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        berhasil2.setForeground(new java.awt.Color(255, 255, 255));
        berhasil2.setText("Demi Keamanan Jaga Informasi Pin ATM anda!!!");
        jPanel1.add(berhasil2);
        berhasil2.setBounds(110, 220, 590, 29);

        berhasil.setBackground(new java.awt.Color(255, 255, 255));
        berhasil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        berhasil.setForeground(new java.awt.Color(255, 255, 255));
        berhasil.setText("SELAMAT PIN ANDA BERHASIL DI UBAH");
        jPanel1.add(berhasil);
        berhasil.setBounds(140, 130, 510, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GantiPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GantiPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GantiPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GantiPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GantiPin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel berhasil;
    private javax.swing.JLabel berhasil2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
