/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uts_Denis;

/**
 *
 * @author ASUS
 */
public class Tranfer2 extends javax.swing.JFrame {

    /**
     * Creates new form Tranfer2
     */
    public Tranfer2() {
        initComponents();
        berhasil.setVisible(false);
        sisa.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jumtransfer = new javax.swing.JTextField();
        Benar = new javax.swing.JButton();
        salah = new javax.swing.JButton();
        sisa = new javax.swing.JLabel();
        berhasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(882, 550));
        setMinimumSize(new java.awt.Dimension(882, 550));
        setPreferredSize(new java.awt.Dimension(882, 550));
        setSize(new java.awt.Dimension(882, 550));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Masukkan Jumlah Transfer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(124, 76, 310, 29);

        jumtransfer.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jumtransferInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(jumtransfer);
        jumtransfer.setBounds(120, 140, 410, 50);

        Benar.setText("Benar");
        Benar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenarActionPerformed(evt);
            }
        });
        jPanel1.add(Benar);
        Benar.setBounds(610, 340, 230, 70);

        salah.setText("Batal");
        salah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salahActionPerformed(evt);
            }
        });
        jPanel1.add(salah);
        salah.setBounds(610, 430, 230, 60);

        sisa.setText("----");
        jPanel1.add(sisa);
        sisa.setBounds(110, 450, 330, 20);

        berhasil.setText("Transaksi Berhasil");
        jPanel1.add(berhasil);
        berhasil.setBounds(110, 380, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenarActionPerformed
        // TODO add your handling code here:
        TransferModel tf = new TransferModel();
        InformasiSaldoModel saldo = new InformasiSaldoModel();
        String jmlh = jumtransfer.getText();
        double jmlh2 = Double.parseDouble(jmlh);
        tf.transfer = jmlh2;
        double s = Double.parseDouble(saldo.getSaldo());
        double hasil = s- tf.transfer;
        if(tf != null){
            berhasil.setVisible(true);
            sisa.setVisible(true);
            sisa.setText("SISA SALDO ANDA : Rp "+hasil);
            
        }else{
            sisa.setVisible(false);
            berhasil.setVisible(false);
            
        }
    }//GEN-LAST:event_BenarActionPerformed

    private void jumtransferInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jumtransferInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumtransferInputMethodTextChanged

    private void salahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salahActionPerformed
        new HalamanUtama().setVisible(true);   
        this.setVisible(false);
    }//GEN-LAST:event_salahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tranfer2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Benar;
    private javax.swing.JLabel berhasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumtransfer;
    private javax.swing.JButton salah;
    private javax.swing.JLabel sisa;
    // End of variables declaration//GEN-END:variables
}
